[theme]
primaryColor = "#ff5252"
backgroundColor = "#12141d"
secondaryBackgroundColor = "#1e202d"
textColor = "#e0e6ed"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
